"""FastMCP server exposing the reasoning engine to Claude Code."""

import json
import logging
import os

from fastmcp import FastMCP

from reasoning_engine.db import init_db
from reasoning_engine.dora import select_branches
from reasoning_engine.memory import recall_memory, record_reflection, save_memory
from reasoning_engine.sanitizer import sanitize_content as _sanitize
from reasoning_engine.sessions import (
    check_termination as _check_termination,
    create_session,
    get_active_branches,
    get_consensus_candidates as _get_consensus,
    get_session,
    register_branch as _register_branch,
    score_branch as _score_branch,
    update_branch_status,
)

logger = logging.getLogger("reasoning-engine")

DB_PATH = os.environ.get(
    "REASONING_ENGINE_DB",
    os.path.join(os.path.dirname(__file__), "reasoning.db"),
)

init_db(DB_PATH)

mcp = FastMCP(
    "reasoning-engine",
    instructions="Actor-Critic-Planner-Reflexion reasoning backend for deep research",
)


def _parse_json(raw: str, field_name: str) -> list | dict:
    """Parse a JSON string with a helpful error message on failure."""
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid JSON in '{field_name}': {exc.msg} (pos {exc.pos}). "
            f"Input was: {raw[:200]!r}"
        ) from exc


@mcp.tool()
def init_research_session(query: str) -> str:
    """Create a new research session. Estimates difficulty and returns budget allocation."""
    session = create_session(DB_PATH, query=query)
    session["session_id"] = session.pop("id")
    logger.info(
        "Session created: id=%s difficulty=%.2f strategy=%s",
        session["session_id"], session["difficulty"], session["strategy"],
    )
    return json.dumps(session)


@mcp.tool()
def register_branch(
    session_id: str, trace: str, sources: str = "[]", parent_id: str = "", depth: int = 0
) -> str:
    """Register a new reasoning branch generated by an Actor agent."""
    branch = _register_branch(
        DB_PATH,
        session_id=session_id,
        trace=_parse_json(trace, "trace"),
        sources=_parse_json(sources, "sources"),
        parent_id=parent_id or None,
        depth=depth,
    )
    logger.info("Branch registered: id=%s session=%s depth=%d", branch["id"], session_id, depth)
    return json.dumps({"branch_id": branch["id"], "session_id": session_id})


@mcp.tool()
def score_branch(
    session_id: str,
    branch_id: str,
    q_score: float,
    advantage: float,
    critique: str,
    confidence: float,
) -> str:
    """Record a Critic's dual-signal score for a reasoning branch."""
    _score_branch(DB_PATH, branch_id, q_score, advantage, critique, confidence)
    logger.info("Branch scored: id=%s q=%.2f adv=%.2f conf=%.2f", branch_id, q_score, advantage, confidence)
    return json.dumps({"status": "scored", "branch_id": branch_id})


@mcp.tool()
def select_next_branches(session_id: str) -> str:
    """Run DORA allocation: compute kappa, decide explore vs exploit, return branch decisions."""
    session = get_session(DB_PATH, session_id)
    branches = get_active_branches(DB_PATH, session_id)
    scores = {b["id"]: b["q_score"] for b in branches}
    budget_remaining = session["budget_remaining_steps"]
    result = select_branches(scores, budget_remaining)
    for bid in result.branches_to_prune:
        update_branch_status(DB_PATH, bid, "pruned")
    for bid in result.branches_to_reflect:
        update_branch_status(DB_PATH, bid, "reflecting")
    logger.info(
        "Branches selected: kappa=%.4f allocation=%s continue=%d reflect=%d prune=%d",
        result.kappa, result.allocation,
        len(result.branches_to_continue), len(result.branches_to_reflect), len(result.branches_to_prune),
    )
    return json.dumps({
        "branches_to_continue": result.branches_to_continue,
        "branches_to_reflect": result.branches_to_reflect,
        "branches_to_prune": result.branches_to_prune,
        "allocation": result.allocation,
        "kappa": round(result.kappa, 4),
        "budget_remaining": result.budget_remaining,
    })


@mcp.tool()
def record_reflection_tool(
    session_id: str,
    branch_id: str,
    original_critique: str,
    revision_summary: str,
    score_before: float,
    score_after: float,
) -> str:
    """Store a Reflexion cycle's critique and revision in episodic memory."""
    result = record_reflection(
        DB_PATH, branch_id, session_id, original_critique, revision_summary, score_before, score_after,
    )
    update_branch_status(DB_PATH, branch_id, "active")
    return json.dumps(result)


@mcp.tool()
def check_termination(session_id: str) -> str:
    """Check whether the research session should terminate."""
    session = get_session(DB_PATH, session_id)
    result = _check_termination(DB_PATH, session_id, session["budget_remaining_steps"])
    logger.info("Termination check: session=%s should_terminate=%s reason=%s", session_id, result["should_terminate"], result["reason"])
    return json.dumps(result)


@mcp.tool()
def get_session_state(session_id: str) -> str:
    """Return full session state including all branches and scores."""
    session = get_session(DB_PATH, session_id)
    branches = get_active_branches(DB_PATH, session_id)
    return json.dumps({"session": dict(session), "active_branches": branches})


@mcp.tool()
def consensus_candidates(session_id: str, top_k: int = 3) -> str:
    """Return top-K branches by q_score for final synthesis."""
    candidates = _get_consensus(DB_PATH, session_id, top_k)
    return json.dumps(candidates)


@mcp.tool()
def save_to_memory(session_id: str, query: str, key_learnings: str, domain_tags: str) -> str:
    """Persist episodic memory from a research session for future recall."""
    result = save_memory(
        DB_PATH, session_id, query,
        _parse_json(key_learnings, "key_learnings"),
        _parse_json(domain_tags, "domain_tags"),
    )
    logger.info("Memory saved: id=%s session=%s", result["id"], session_id)
    return json.dumps(result)


@mcp.tool()
def recall_memory_tool(query: str, limit: int = 5) -> str:
    """Retrieve relevant episodic memories from past research sessions."""
    results = recall_memory(DB_PATH, query, limit)
    for r in results:
        r.pop("_relevance", None)
    logger.info("Memory recalled: query=%r results=%d", query, len(results))
    return json.dumps(results)


@mcp.tool()
def sanitize_content(raw_text: str) -> str:
    """Sanitize web-crawled content, stripping HTML, scripts, and prompt injection patterns."""
    cleaned = _sanitize(raw_text)
    return json.dumps({"cleaned": cleaned})
