"""FastMCP server exposing the reasoning engine to Claude Code."""

import json
import logging
import os
from typing import Any

from mcp.server.fastmcp import FastMCP

from reasoning_engine.db import init_db
from reasoning_engine.dora import select_branches
from reasoning_engine.memory import recall_memory, record_reflection, save_memory
from reasoning_engine.research import evidence_gap_questions, plan_research_angles
from reasoning_engine.sanitizer import sanitize_content as _sanitize
from reasoning_engine.sessions import (
    apply_planning_result,
    create_session,
    get_active_branches,
    get_branch_for_session,
    get_session,
    get_session_branches,
)
from reasoning_engine.sessions import (
    check_termination as _check_termination,
)
from reasoning_engine.sessions import (
    get_consensus_candidates as _get_consensus,
)
from reasoning_engine.sessions import (
    register_branch as _register_branch,
)
from reasoning_engine.sessions import (
    score_branch as _score_branch,
)
from reasoning_engine.validation import (
    MAX_ANGLES,
    MAX_CRITIQUE_CHARS,
    MAX_LEARNING_CHARS,
    MAX_LEARNINGS,
    MAX_MEMORY_LIMIT,
    MAX_QUERY_CHARS,
    MAX_TAG_CHARS,
    MAX_TAGS,
    MAX_TOP_K,
    MAX_TRACE_STEP_CHARS,
    MAX_TRACE_STEPS,
    validate_limited_int,
    validate_non_negative_int,
    validate_score,
    validate_sources,
    validate_string_list,
    validate_text,
)
from reasoning_engine.verifiable.profiles import classify_research_mode
from reasoning_engine.verifiable.quality import run_quality_gate
from reasoning_engine.verifiable.service import VerifiableResearchService

logger = logging.getLogger("reasoning-engine")

DB_PATH = os.environ.get(
    "REASONING_ENGINE_DB",
    os.path.join(os.path.dirname(__file__), "reasoning.db"),
)
RUNS_DIR = os.environ.get(
    "REASONING_ENGINE_RUNS_DIR",
    os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "runs"),
)

init_db(DB_PATH)

mcp = FastMCP(
    "reasoning-engine",
    instructions="Actor-Critic-Planner-Reflexion reasoning backend for deep research",
)


def _parse_json(raw: str, field_name: str) -> list | dict:
    """Parse a JSON string with a helpful error message on failure."""
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in '{field_name}': {exc.msg} (pos {exc.pos})") from exc


def _json_response(payload: dict[str, Any] | list[Any]) -> str:
    return json.dumps(payload, ensure_ascii=False)


@mcp.tool()
def init_research_session(query: str) -> str:
    """Create a new research session. Estimates difficulty and returns budget allocation."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    session = create_session(DB_PATH, query=query)
    session["session_id"] = session.pop("id")
    logger.info(
        "Session created: id=%s difficulty=%.2f strategy=%s",
        session["session_id"],
        session["difficulty"],
        session["strategy"],
    )
    return _json_response(session)


@mcp.tool()
def register_branch(
    session_id: str, trace: str, sources: str = "[]", parent_id: str = "", depth: int = 0
) -> str:
    """Register a new reasoning branch generated by an Actor agent."""
    session = get_session(DB_PATH, session_id)
    depth = validate_non_negative_int(depth, "depth", session["budget_max_depth"])
    trace_data = validate_string_list(
        _parse_json(trace, "trace"),
        "trace",
        max_items=MAX_TRACE_STEPS,
        max_item_chars=MAX_TRACE_STEP_CHARS,
    )
    source_data = validate_sources(_parse_json(sources, "sources"))
    branch = _register_branch(
        DB_PATH,
        session_id=session_id,
        trace=trace_data,
        sources=source_data,
        parent_id=parent_id or None,
        depth=depth,
    )
    logger.info("Branch registered: id=%s session=%s depth=%d", branch["id"], session_id, depth)
    return _json_response({"branch_id": branch["id"], "session_id": session_id})


@mcp.tool()
def score_branch(
    session_id: str,
    branch_id: str,
    q_score: float,
    advantage: float,
    critique: str,
    confidence: float,
) -> str:
    """Record a Critic's dual-signal score for a reasoning branch."""
    get_branch_for_session(DB_PATH, branch_id, session_id)
    q_score = validate_score(q_score, "q_score")
    advantage = validate_score(advantage, "advantage")
    confidence = validate_score(confidence, "confidence")
    critique = validate_text(critique, "critique", MAX_CRITIQUE_CHARS, allow_empty=True)
    _score_branch(
        DB_PATH, branch_id, q_score, advantage, critique, confidence, session_id=session_id
    )
    logger.info(
        "Branch scored: id=%s q=%.2f adv=%.2f conf=%.2f",
        branch_id,
        q_score,
        advantage,
        confidence,
    )
    return _json_response({"status": "scored", "branch_id": branch_id})


@mcp.tool()
def select_next_branches(session_id: str) -> str:
    """Run DORA allocation: compute kappa, decide explore vs exploit, return branch decisions."""
    session = get_session(DB_PATH, session_id)
    branches = get_active_branches(DB_PATH, session_id)
    scores = {b["id"]: b["q_score"] for b in branches}
    budget_remaining = session["budget_remaining_steps"]
    result = select_branches(scores, budget_remaining)
    apply_planning_result(
        DB_PATH,
        session_id,
        result.branches_to_reflect,
        result.branches_to_prune,
        result.budget_remaining,
    )
    logger.info(
        "Branches selected: kappa=%.4f allocation=%s continue=%d reflect=%d prune=%d",
        result.kappa,
        result.allocation,
        len(result.branches_to_continue),
        len(result.branches_to_reflect),
        len(result.branches_to_prune),
    )
    return _json_response(
        {
            "branches_to_continue": result.branches_to_continue,
            "branches_to_reflect": result.branches_to_reflect,
            "branches_to_prune": result.branches_to_prune,
            "allocation": result.allocation,
            "kappa": round(result.kappa, 4),
            "budget_remaining": result.budget_remaining,
        }
    )


@mcp.tool()
def record_reflection_tool(
    session_id: str,
    branch_id: str,
    original_critique: str,
    revision_summary: str,
    score_before: float,
    score_after: float,
) -> str:
    """Store a Reflexion cycle's critique and revision in episodic memory."""
    get_branch_for_session(DB_PATH, branch_id, session_id)
    original_critique = validate_text(
        original_critique,
        "original_critique",
        MAX_CRITIQUE_CHARS,
        allow_empty=True,
    )
    revision_summary = validate_text(revision_summary, "revision_summary", MAX_CRITIQUE_CHARS)
    score_before = validate_score(score_before, "score_before")
    score_after = validate_score(score_after, "score_after")
    result = record_reflection(
        DB_PATH,
        branch_id,
        session_id,
        original_critique,
        revision_summary,
        score_before,
        score_after,
    )
    return _json_response(result)


@mcp.tool()
def check_termination(session_id: str) -> str:
    """Check whether the research session should terminate."""
    session = get_session(DB_PATH, session_id)
    result = _check_termination(DB_PATH, session_id, session["budget_remaining_steps"])
    logger.info(
        "Termination check: session=%s should_terminate=%s reason=%s",
        session_id,
        result["should_terminate"],
        result["reason"],
    )
    return _json_response(result)


@mcp.tool()
def get_session_state(session_id: str) -> str:
    """Return full session state including all branches and scores."""
    session = get_session(DB_PATH, session_id)
    branches = get_session_branches(DB_PATH, session_id)
    return _json_response({"session": dict(session), "branches": branches})


@mcp.tool()
def consensus_candidates(session_id: str, top_k: int = 3) -> str:
    """Return top-K branches by q_score for final synthesis."""
    top_k = validate_limited_int(top_k, "top_k", 1, MAX_TOP_K)
    candidates = _get_consensus(DB_PATH, session_id, top_k)
    return _json_response(candidates)


@mcp.tool()
def save_to_memory(session_id: str, query: str, key_learnings: str, domain_tags: str) -> str:
    """Persist episodic memory from a research session for future recall."""
    get_session(DB_PATH, session_id)
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    learnings = validate_string_list(
        _parse_json(key_learnings, "key_learnings"),
        "key_learnings",
        max_items=MAX_LEARNINGS,
        max_item_chars=MAX_LEARNING_CHARS,
    )
    tags = validate_string_list(
        _parse_json(domain_tags, "domain_tags"),
        "domain_tags",
        max_items=MAX_TAGS,
        max_item_chars=MAX_TAG_CHARS,
    )
    result = save_memory(
        DB_PATH,
        session_id,
        query,
        learnings,
        tags,
    )
    logger.info("Memory saved: id=%s session=%s", result["id"], session_id)
    return _json_response(result)


@mcp.tool()
def recall_memory_tool(query: str, limit: int = 5) -> str:
    """Retrieve relevant episodic memories from past research sessions."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    limit = validate_limited_int(limit, "limit", 1, MAX_MEMORY_LIMIT)
    results = recall_memory(DB_PATH, query, limit)
    for r in results:
        r.pop("_relevance", None)
    logger.info("Memory recalled: query=%r results=%d", query, len(results))
    return _json_response(results)


@mcp.tool()
def sanitize_content(raw_text: str) -> str:
    """Sanitize web-crawled content, stripping HTML, scripts, and prompt injection patterns."""
    raw_text = validate_text(raw_text, "raw_text", MAX_QUERY_CHARS * 4, allow_empty=True)
    cleaned = _sanitize(raw_text)
    return _json_response({"cleaned": cleaned})


@mcp.tool()
def plan_research_angles_tool(query: str, max_angles: int = 6) -> str:
    """Return prioritized research angles and starter questions for a query."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    max_angles = validate_limited_int(max_angles, "max_angles", 1, MAX_ANGLES)
    return _json_response(plan_research_angles(query, max_angles))


@mcp.tool()
def evidence_gap_questions_tool(query: str, claims: str) -> str:
    """Generate verification questions for claims before final synthesis."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    claim_list = validate_string_list(
        _parse_json(claims, "claims"),
        "claims",
        max_items=MAX_TRACE_STEPS,
        max_item_chars=MAX_TRACE_STEP_CHARS,
    )
    return _json_response(evidence_gap_questions(query, claim_list))


def _research_service() -> VerifiableResearchService:
    return VerifiableResearchService(DB_PATH, RUNS_DIR)


@mcp.tool()
def start_research_run(query: str, mode: str = "standard", profile: str = "auto") -> str:
    """Create a verifiable research run with selected mode and profile."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    run = _research_service().start_run(query=query, mode=mode, profile=profile)
    return _json_response(run.to_dict())


@mcp.tool()
def classify_research_mode_tool(query: str, requested_mode: str = "standard") -> str:
    """Classify the research mode, escalating high-stakes queries."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    return _json_response({"mode": classify_research_mode(query, requested_mode)})


@mcp.tool()
def scholar_search_tool(run_id: str, query: str, limit: int = 10) -> str:
    """Search Scholar Gateway through the verifiable research service."""
    run_id = validate_text(run_id, "run_id", 128)
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    limit = validate_limited_int(limit, "limit", 1, 25)
    payload = _research_service().scholar_search(run_id, query, limit)
    payload.pop("evidence_records", None)
    return _json_response(payload)


@mcp.tool()
def get_scholar_auth_status() -> str:
    """Return Scholar Gateway auth status without exposing token values."""
    return _json_response(
        {
            "live_enabled": os.environ.get("SCHOLAR_GATEWAY_LIVE") == "1",
            "has_env_token": bool(os.environ.get("SCHOLAR_GATEWAY_ACCESS_TOKEN")),
            "token_storage": "environment_or_keyring",
        }
    )


@mcp.tool()
def run_research_pipeline_tool(
    query: str,
    draft: str,
    mode: str = "standard",
    profile: str = "auto",
) -> str:
    """Run the MVP verifiable research pipeline and export an attested run pack."""
    query = validate_text(query, "query", MAX_QUERY_CHARS)
    draft = validate_text(draft, "draft", MAX_QUERY_CHARS * 4)
    return _json_response(
        _research_service().run_research_pipeline(
            query=query,
            draft=draft,
            mode=mode,
            profile=profile,
        )
    )


@mcp.tool()
def run_quality_gate_tool(run_id: str) -> str:
    """Run the quality gate for persisted claims and verifications."""
    run_id = validate_text(run_id, "run_id", 128)
    store = _research_service().store
    claims = store.list_claims(run_id)
    verifications = store.list_verifications(run_id)
    gaps = store.list_gaps(run_id)
    result = run_quality_gate(run_id, claims, verifications, gaps)
    return _json_response(result)


@mcp.tool()
def export_run_pack_tool(query: str, draft: str, mode: str = "standard", profile: str = "auto") -> str:
    """Run the pipeline and return the exported run-pack path."""
    return run_research_pipeline_tool(query, draft, mode, profile)
